apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 80
      protocol: TCP
      targetPort: 8000
      nodePort: 30001 # 30.000 - 30.767
